function createfigure(X1, U1, V1, W1, Vertices1, Faces1, X2, Y1, Z1)
%CREATEFIGURE(X1, U1, V1, W1, VERTICES1, FACES1, X2, Y1, Z1)
%  X1:  quiver3 x
%  U1:  quiver3 u
%  V1:  quiver3 v
%  W1:  quiver3 w
%  VERTICES1:  patch vertices
%  FACES1:  patch faces
%  X2:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 27-Oct-2017 08:56:40

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create quiver3
quiver3(X1,X1,X1,U1,V1,W1,'Color',[1 0 0]);

% Create text
text('Parent',axes1,'String','x','Position',[0 -22.5 -22.5]);

% Create text
text('Parent',axes1,'String','y','Position',[-22.5 0 -22.5]);

% Create text
text('Parent',axes1,'String','z','Position',[-22.5 -22.5 0]);

% Create patch
patch('Parent',axes1,'Clipping','off','Vertices',Vertices1,'Faces',Faces1,...
    'FaceColor',[0.862745098039216 0.862745098039216 0.862745098039216],...
    'EdgeColor','none');

% Create plot3
plot3(X2,Y1,Z1,'Clipping','off','Color',[0 0 0]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F1',...
    'Position',[16 -21.5461646096066 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F2',...
    'Position',[42.5461646096066 -15 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F3',...
    'Position',[21 -8.45383539039338 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F4',...
    'Position',[2.54616460960662 10 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F5',...
    'Position',[-4 31.5461646096066 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F6',...
    'Position',[-10.5461646096066 5 37.5]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F7',...
    'Position',[-4.2549600986763 -8.54446031622283 -1.54616460960662]);

% Create text
text('Parent',axes1,'Clipping','on','HorizontalAlignment','center',...
    'String','F8',...
    'Position',[-4.2549600986763 -8.54446031622283 76.5461646096066]);

view(axes1,[30 30]);
axis(axes1,'tight');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','DataAspectRatio',[1 1 1],...
    'PlotBoxAspectRatio',[1.20819877304678 1 1.84539821564188]);
